- block:
    - name: Install git-review
      package:
        name:
          - git-review
          # This should only be needed with the podman backend
          - catatonit
        state: present
      become: true
  when: not local

- name: Setup Tutorial Execution
  import_role:
    name: setup-tutorial

- name: Run quick-start tutorial
  import_tasks: quick-start.yaml

- name: Run admin tutorial
  import_tasks: admin.yaml

- name: Run tracing tutorial
  import_tasks: tracing.yaml
