# Copyright (c) 2019 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y \
  && apt-get upgrade -y \
  && apt-get install -y python3.11 \
  && apt-get install -y python3-pip \
  && apt-get install -y python3.11-dev \
  && apt-get install -y gdb \
  && apt-get install -y curl
COPY bindep.txt /tmp
RUN python3.11 -m pip install nox bindep pystack
RUN bindep --brief -f /tmp/bindep.txt test | xargs apt-get install -y
SHELL ["/bin/bash", "-c"]
WORKDIR /
ENTRYPOINT ["/bin/bash"]